package accountinfo;

import java.io.BufferedOutputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 *
 * @author RIDDLE
 * 
 */
public class AccountEntry extends javax.swing.JFrame {

    private String name;
    private String address;
    private String pan;
    private boolean isSelf;
    private List<AccountData> accountData;
    private final List<DealData> dealData;

    public AccountEntry(List accountData, List dealData) {
        initComponents();
        setTitle("Account Entry");
        if (accountData == null) {
            accountData = new ArrayList();
        } else {
            this.accountData = accountData;
        }
        this.dealData = dealData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        addressInput = new javax.swing.JTextArea();
        panInput = new javax.swing.JTextField();
        selfCheck = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setText("ACCOUNT ENTRY");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 69, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 121, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("PAN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 241, -1, -1));

        nameInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(nameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 69, 183, -1));

        addressInput.setColumns(20);
        addressInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressInput.setRows(5);
        addressInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(addressInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 120, 183, 103));

        panInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(panInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 241, 186, -1));

        selfCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(selfCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 278, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Self");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 278, -1, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveData(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 328, -1, -1));

        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setText("BACK");
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 328, 52, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //save new account data to the file
    private void saveData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveData

        name = nameInput.getText();
        address = addressInput.getText();
        pan = panInput.getText();
        isSelf = selfCheck.isSelected();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fields required");
            return;
        }
        if (address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fields required");
            return;
        }
        if (pan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fields required");
            return;
        }

        File file = new File("account data.mno");
    
        System.out.println(file.exists());
        if (!file.exists()) {
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(AccountEntry.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        String data = name + ":" + address + ":" + pan + ":" + isSelf;
        AccountData accountData = new AccountData(name, address, pan, isSelf);
        boolean result = false;
        if (isSelf) {
            for (AccountData accData : this.accountData) {
                if (accData.isIsSelf()) {
                    accountData.setId(1);
                    result = true;
                    break;
                }
            }
            if (!result) {
                accountData.setId(0);
            }
        }
        data = data + ":" + accountData.getId();
        
        this.accountData.add(accountData);
        try {
            writeToFile(file, data);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AccountEntry.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AccountEntry.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(this, "Saved!!");


    }//GEN-LAST:event_saveData

    //jump back to the previous window
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        try {
            new dash_board(this.accountData, this.dealData).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AccountEntry.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
//            new AccountEntry().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressInput;
    private javax.swing.JButton backButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField panInput;
    private javax.swing.JCheckBox selfCheck;
    // End of variables declaration//GEN-END:variables

    //write account data to the file
    private void writeToFile(File file, String data) throws FileNotFoundException, IOException {
        byte[] dataBytes = new CipherData().encrypter(data.getBytes());
        DataOutputStream outputStream = new DataOutputStream(new BufferedOutputStream(new FileOutputStream(file, true)));
        outputStream.writeInt(dataBytes.length);
        outputStream.write(dataBytes);
        outputStream.flush();
        outputStream.close();
        clearInputs();

    }

    //clear all the input fields
    private void clearInputs() {
        nameInput.setText("");
        panInput.setText("");
        addressInput.setText("");
        selfCheck.setSelected(false);
    }

}
